on:
  pull_request:
    branches:
      - master

name: Generate packages

jobs:
  build:
    name: Sign packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Generate and sign packages"
        id: sign
        run: |
          echo -n "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode > binary.asc
          gpg --import --passphrase ${{ secrets.GPG_PASSPHRASE }} binary.asc 
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          gpg --default-key "contact@jingk.ai" -abs -o - Release > Release.gpg
          gpg --default-key "contact@jingk.ai" --clearsign -o - Release > InRelease
      - name: "Push signed packages and release to github"
        id: push
        uses: stefanzweifel/git-auto-commit-action@v4
        commit_message: "Signed and pushed packages"
        commit_user_name: "xlanor"
        commit_user_email: "contact@jingk.ai"
        
